name: 'nyc_taxi_dbt'
version: '1.0.0'

profile: 'nyc_taxi_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



models:
  nyc_taxi_dbt:
    staging:
      +materialized: view
    core:
      +materialized: table
    intermediate:
      +materialized: view
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true